LOAD DATA LOCAL INFILE "FOOD.dat"
INTO TABLE FOOD
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';
LOAD DATA LOCAL INFILE "CUSTOMER.dat"
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';
LOAD DATA LOCAL INFILE "DELIVERY_GROUP.dat"
INTO TABLE DELIVERY_GROUP
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';
LOAD DATA LOCAL INFILE "ORDERS.dat"
INTO TABLE ORDERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r';
LOAD DATA LOCAL INFILE "ITEM.dat"
INTO TABLE ITEM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';